# Dev
# backend:
#   name: test-repo
#   site_domain: cms.netlify.com

backend:
  name: git-gateway
  branch: netlify-cms

# Prod
# backend:
#   name: git-gateway
#   branch: master

locale: fr
logo_url: https://www.110lab.fr/images/110lab-logo.svg

publish_mode: editorial_workflow
# Media files will be stored in the repo under static/images/uploads
media_folder: "static/images/uploads"
# The src attribute for uploaded media will begin with /images/uploads
public_folder: "/images/uploads"

collections:
  - name: "beers"
    label: "Bières"
    folder: "content/french/beers"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - label: Mise en page
        name: layout
        widget: hidden
        default: beers

      - label: Nom
        name: title
        widget: string

      - label: Date du brassin
        name: date
        widget: datetime

      - label: Featured Image
        name: images
        widget: list
        field:
          label: Image
          name: image
          widget: image

      - label: Description de la bière
        name: body
        widget: markdown

  - name: blog
    label: Blog
    folder: content/french/blog
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - label: Mise en page
        name: layout
        widget: hidden
        default: blog

      - label: Titre
        name: title
        widget: string

      - label: Date de publication
        name: date
        widget: datetime

      - label: Image
        name: image
        widget: image

      - label: Corp
        name: body
        widget: markdown
